--What is the total revenue generated by each product type?
SELECT 
    SUM(standard_amt_usd) AS standard_revenue,
    SUM(gloss_amt_usd) AS gloss_revenue,
    SUM(poster_amt_usd) AS poster_revenue
FROM orders;

--What are the top 10 orders by total revenue?
SELECT TOP 10
    id,
    account_id,
    total_amt_usd AS total_revenue
FROM orders
ORDER BY total_amt_usd DESC;

--What is the total revenue by region?
SELECT
    r.name AS region,
    SUM(o.total_amt_usd) AS total_revenue
FROM orders o
JOIN accounts a ON o.account_id = a.id
JOIN sales_reps s ON a.sales_rep_id = s.id
JOIN region r ON s.region_id = r.id
GROUP BY r.name;

--Who are the top 10 customers by total revenue?
SELECT TOP 10
    a.name AS customers,
    SUM(o.total_amt_usd) AS total_revenue
FROM orders o
JOIN accounts a ON o.account_id = a.id
GROUP BY a.name
ORDER BY total_revenue DESC;

--How many customers does each sales representative manage?
SELECT 
    s.name,
    COUNT(a.id) AS total_customers
FROM accounts a
JOIN sales_reps s ON a.sales_rep_id = s.id
GROUP BY s.name;

-- Categorize customers by total revenue tier (High/Medium/Low)?
SELECT 
	a.name,
	SUM(o.total_amt_usd) AS total_spent,
	CASE 
		WHEN SUM(o.total_amt_usd) > 100000 THEN 'High'
		WHEN SUM(o.total_amt_usd) > 50000 THEN 'Medium'
		ELSE 'Low'
	END AS customer_tier
FROM orders o
JOIN accounts a ON o.account_id = a.id
GROUP BY a.name;

--What is the total revenue generated by each sales representative?
SELECT 
	s.name,
	SUM(o.total_amt_usd) AS total_revenue
FROM orders o
JOIN accounts a ON o.account_id = a.id
JOIN sales_reps s ON a.sales_rep_id = s.id
GROUP BY s.name;

--Which sales reps have generated more than $500,000 in total revenue?
SELECT 
	s.name,
	SUM(o.total_amt_usd) AS total_revenue
FROM orders o
JOIN accounts a ON o.account_id = a.id
JOIN sales_reps s ON a.sales_rep_id = s.id
GROUP BY s.name
HAVING SUM(o.total_amt_usd) > 500000;

--How many web events occurred through each channel?
SELECT 
	channel,
	COUNT(id) AS total_events
FROM web_events
GROUP BY channel;

--Which accounts have the most web activity?
SELECT TOP 10
	a.name,
	COUNT(w.id) AS total_events
FROM web_events w
JOIN accounts a ON w.account_id = a.id
GROUP BY a.name
ORDER BY total_events DESC;

-- Which customers have high web engagement but low order frequency?
SELECT TOP 10
	a.name,
	COUNT(DISTINCT w.id) AS web_events,
	COUNT(DISTINCT o.id) AS total_orders
FROM accounts a
LEFT JOIN web_events w ON a.id = w.account_id
LEFT JOIN orders o ON a.id = o.account_id
GROUP BY a.name;

--Create an email list with formatted customer names and clean website domains?
SELECT 
	name,
	LOWER(REPLACE(name, ' ', '')) + '@' + 
	REPLACE(website, 'www.', '') AS email_address
FROM accounts;
--Create an email list using customer names and website domains